FROM node:9-alpine

# Create app directory
WORKDIR app

# Copy app src code to the image 
COPY src/ .

WORKDIR src

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

EXPOSE 8080
CMD [ "npm", "start" ]
