---
swagger: "2.0"
info:
  description: "Data Utility Evaluator"
  version: "0.2.1"
  title: "Data Utility Evaluator API"
  contact:
    email: "pierluigi.plebani@polimi.it"
  license:
    name: "TBD"
host: "localhost:8080"
basePath: "/ditas-project/DataUtilityRefinement/0.2.1"
tags:
- name: "Data Utility"
  description: "Definition of data utility"
- name: "VDC-CAF"
  description: "Virtual Data Container CAF"
schemes:
- "https"
paths:
  /datautilityrefinement:
    post:
      summary: "recalculate the data utility based on the application"
      description: "By passing the DataUtility values and the application it returns\
        \ new DataUtility values depending on the application"
      operationId: "refinement"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "datautility"
        description: "data utility values"
        required: true
        schema:
          $ref: "#/definitions/RefinementRequest"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/DataUtility"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  DataUtility:
    type: "object"
    required:
    - "URL"
    - "accuracy"
    - "completeness"
    - "consistency"
    - "timeliness"
    properties:
      URL:
        type: "string"
        format: "url"
        example: "http://mydatasource/pippo"
      accuracy:
        type: "number"
        format: "float"
        example: 0.1
      consistency:
        type: "number"
        format: "float"
        example: 0.1
      completeness:
        type: "number"
        format: "float"
        example: 0.1
      timeliness:
        type: "number"
        format: "float"
        example: 0.1
    example:
      timeliness: 0.1
      accuracy: 0.1
      completeness: 0.1
      consistency: 0.1
      URL: "http://mydatasource/pippo"
  RefinementRequest:
    type: "object"
    required:
    - "application"
    - "datautility"
    properties:
      application:
        type: "string"
        enum:
        - "regression"
        - "classification"
        - "clustering"
        - "associationrules"
      datautility:
        $ref: "#/definitions/DataUtility"
    example:
      datautility:
        timeliness: 0.1
        accuracy: 0.1
        completeness: 0.1
        consistency: 0.1
        URL: "http://mydatasource/pippo"
      application: "regression"
