---
swagger: "2.0"
info:
  description: "Data Utility Refinement"
  version: "0.2.1"
  title: "Data Utility Refinement API"
  contact:
    email: "pierluigi.plebani@polimi.it"
  license:
    name: "TBD"
host: "virtserver.swaggerhub.com"
basePath: "/ditas-project/DataUtilityRefinement/0.2.1"
tags:
- name: "Data Utility"
  description: "Definition of data utility"
schemes:
- "https"
paths:
  /datautility:
    get:
      summary: "recalculate the data utility based on the application"
      description: "By passing the DataUtility values and the application it returns\
        \ new DataUtility values depending on the application"
      operationId: "refinement"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "datautility"
        description: "data utility values"
        required: true
        schema:
          $ref: "#/definitions/RefinementRequest"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/DataUtility"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Default"
definitions:
  RefinementRequest:
    type: "object"
    required:
    - "application"
    - "datautility"
    properties:
      application:
        type: "string"
        enum:
        - "regression,"
        - "classification"
        - "clustering"
        - "associationrules"
      datautility:
        $ref: "#/definitions/DataUtility"
    example:
      datautility:
        timeliness: 0.1
        accuracy: 0.1
        completeness: 0.1
        consistency: 0.1
        URL: "http://mydatasource/pippo"
      application: "regression,"
  DataUtility:
    type: "object"
    required:
    - "accuracy"
    - "completeness"
    - "consistency"
    - "timeliness"
    properties:
      URL:
        type: "string"
        format: "url"
        example: "http://mydatasource/pippo"
      accuracy:
        type: "number"
        format: "float"
        example: 0.1
      consistency:
        type: "number"
        format: "float"
        example: 0.1
      completeness:
        type: "number"
        format: "float"
        example: 0.1
      timeliness:
        type: "number"
        format: "float"
        example: 0.1
    example:
      timeliness: 0.1
      accuracy: 0.1
      completeness: 0.1
      consistency: 0.1
      URL: "http://mydatasource/pippo"
